name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: toy-backend
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: toy-backend
          path: ./artifacts

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy JAR to server
        run: |
          scp ./artifacts/*.jar ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SSH_USER }}/toy-backend/toy-backend.jar

      - name: Restart app on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # 기존 프로세스 종료
            pkill -f 'java -jar.*toy-backend' || true
            sleep 5
          
            # 새 앱 시작
            cd /home/${{ secrets.SSH_USER }}/toy-backend
            nohup java -jar toy-backend.jar > app.log 2>&1 &
          
            # 프로세스 시작 확인
            sleep 10
            if pgrep -f 'java -jar.*toy-backend.jar' > /dev/null; then
              echo "Application started successfully"
            else
              echo "Failed to start application"
              exit 1
            fi
          EOF